module utils;

String css = `body {
    height: 100%;
    width: 100%;
    margin: 0;
    padding: 0;
    font-family: 'Roboto';
    background-color: #274156;
    }
    
    @keyframes arrow {
    from {
        transform: translateY(0px);
    }
    to {
        transform: translateY(15px);
    }
    }

    .wrapper {
    display: grid;
    background-color: #274156;
    place-items: center;
    height: 100%;
    }

    @font-face {
        font-family: 'Roboto';
    };`;